# Generated by Django 3.1.2 on 2021-01-07 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210107_1433'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
