# Generated by Django 3.1.2 on 2021-01-10 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='weight',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.customer'),
        ),
    ]
