# Generated by Django 3.1.2 on 2021-01-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210110_1533'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weight',
            options={'verbose_name_plural': 'Weight'},
        ),
        migrations.AlterField(
            model_name='weight',
            name='inputted_weight',
            field=models.FloatField(max_length=5, null=True),
        ),
    ]
