# Generated by Django 3.1.2 on 2021-01-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210110_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='date_of_entry',
            field=models.DateField(auto_now=True),
        ),
    ]
