# Generated by Django 3.1.2 on 2021-01-10 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210110_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='date_of_entry',
            field=models.DateField(auto_now_add=True),
        ),
    ]
