# Generated by Django 3.1.2 on 2021-01-10 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210110_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.customer'),
        ),
    ]
