# Generated by Django 3.1.2 on 2021-01-11 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_calories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calories',
            options={'verbose_name_plural': 'Calories'},
        ),
        migrations.CreateModel(
            name='StrengthRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.CharField(choices=[('Deadlift', 'Deadlift'), ('Squat', 'Squat'), ('Bench Press', 'Bench Press'), ('Overhead Press', 'Overhead Press')], max_length=20, null=True)),
                ('weight_record', models.FloatField(null=True)),
                ('date_of_record', models.DateField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.customer')),
            ],
        ),
    ]
