# Generated by Django 3.1.2 on 2021-01-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210111_1721'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='strengthrecords',
            options={'verbose_name_plural': 'Strength Records'},
        ),
        migrations.AddField(
            model_name='customer',
            name='bench_press_record',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='deadlift_record',
            field=models.FloatField(null=True),
        ),
    ]
