# Generated by Django 3.1.2 on 2021-01-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20210112_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='overhead_press',
            field=models.FloatField(null=True),
        ),
    ]
