# Generated by Django 3.1.2 on 2021-01-14 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_customer_overhead_press'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='overhead_press',
            new_name='overhead_press_record',
        ),
    ]
