# Generated by Django 3.1.2 on 2021-01-15 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_customer_targets_enabled'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.AlterField(
            model_name='customer',
            name='targets_enabled',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
