# Generated by Django 3.1.2 on 2021-01-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20210115_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='next_calories',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='previous_calories',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
