# Generated by Django 3.1.2 on 2021-01-15 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20210115_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='next_calories',
            new_name='track_calorie_data',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='previous_calories',
        ),
    ]
