# Generated by Django 3.1.2 on 2021-01-15 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_customer_strength_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='weight_data',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
    ]
