# Generated by Django 3.1.2 on 2021-01-15 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20210115_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='weight_data',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
