# Generated by Django 3.1.2 on 2021-01-15 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20210115_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='calorie_data',
            field=models.IntegerField(default=5, null=True),
        ),
    ]
