# Generated by Django 3.1.2 on 2021-01-15 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20210115_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='calorie_data',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='strength_data',
            field=models.IntegerField(default=0),
        ),
    ]
