# Generated by Django 3.1.2 on 2021-01-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20210115_2158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='calorie_data',
            new_name='calorie_data_range',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='strength_data',
            new_name='strength_data_range',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='weight_data',
            new_name='weight_data_range',
        ),
        migrations.AddField(
            model_name='customer',
            name='bench_press_target',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='deadlift_target',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='overhead_press_target',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='squat_target',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='targets_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
