# Generated by Django 3.1.2 on 2021-01-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20210116_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='calorie_data_range',
            new_name='calorie_data_date_range',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='strength_data_range',
            new_name='strength_data_date_range',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='weight_data_range',
        ),
        migrations.AddField(
            model_name='customer',
            name='weight_data_date_range',
            field=models.IntegerField(default=0),
        ),
    ]
