# Generated by Django 3.1.2 on 2021-01-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20210116_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='weight_target',
            field=models.FloatField(null=True),
        ),
    ]
