# Generated by Django 3.1.2 on 2021-01-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_customer_weight_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='current_weight',
            field=models.FloatField(null=True),
        ),
    ]
